#!/bin/bash

#BlackCat Rev. 01

echo "### INSTALAÇÃO ELECTRUM BITCOIN WALLET 2.7.12 ###"
echo " "
echo "Testado nas seguintes distribuições:"
echo "- Ubuntu 16.04"
echo " "

sudo apt-get install python-qt4 python-pip
sudo pip install https://download.electrum.org/2.7.12/Electrum-2.7.12.tar.gz

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read
