#!/bin/bash

#BlackCat Rev. 01

echo "### INSTALAÇÃO EVERPAD ###"
echo " "

sudo add-apt-repository ppa:nvbn-rm/ppa
sudo apt-get update 
sudo apt-get install everpad -y

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read
