#!/bin/bash

#BlackCat Rev. 01

echo "### INSTALAÇÃO GOOGLE-CHROME ###"
echo " "

sudo chmod o+w /etc/apt/sources.list
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sudo apt-get update && sudo apt-get install google-chrome-stable -y

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read