#!/bin/bash

#BlackCat Rev. 01

echo "### INSTALAÇÃO ORACLE JAVA 1.7 ###"
echo " "

sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java7-installer -y
echo " "

echo "Processo Concluído!!! Tecle ENTER"
read
