#!/bin/bash

#BlackCat Rev. 01

echo "Não está pronto."
echo "Volte em breve ou ajude a fazer esse script."

#baixar
#extrair
#sudo apt-get install libswitch-perl
#apt-get install cpanminus
#cpanm WWW::Mechanize
#cpanm WWW::Mechanize::TreeBuilder

read
