#!/bin/bash

#BlackCat Rev. 01
#http://kicad-pcb.org/download/ubuntu/

echo "### INSTALAÇÃO KICAD ###"
echo " "
echo "Testado nas seguintes distribuições:"
echo "- Ubuntu 16.04"
echo " "

sudo add-apt-repository --yes ppa:js-reynaud/kicad-4
sudo apt update
sudo apt install kicad

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read
