#!/bin/bash

#BlackCat Rev. 01

echo "### INSTALAÇÃO PEEK ###"
echo " "

cd .cacheappinstall && wget https://github.com/phw/peek/releases/download/v0.7.2/peek-0.7.2-Linux.deb
cd .cacheappinstall && sudo dpkg -i peek*.deb
sudo apt-get -f install

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read
