#!/bin/bash

#BlackCat Rev. 01

echo "### INSTALAÇÃO QBITTORRENT ###"
echo " "

sudo add-apt-repository ppa:qbittorrent-team/qbittorrent-stable
sudo apt-get update
sudo apt-get install qbittorrent

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read