#!/bin/bash

echo "BlackCat Rev. 01"
echo " "

echo "### INSTALAÇÃO SIMPLE SCREEN RECORDER ###"
echo " "
echo "Testado nas seguintes distribuições:"
echo "- Ubuntu 16.04"
echo " "

sudo add-apt-repository ppa:maarten-baert/simplescreenrecorder
sudo apt-get update
sudo apt-get install simplescreenrecorder simplescreenrecorder-lib:i386 -y

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read