#!/bin/bash

echo "BlackCat Rev. 01"
echo " "

echo "### INSTALAÇÃO SKYPE PIDGIN ###"
echo " "
echo "Testado nas seguintes distribuições:"
echo "- Ubuntu 16.04"
echo " "

sudo apt-get install libpurple-dev libjson-glib-dev cmake gcc
sudo cd /.cacheappinstall/ && git clone git://github.com/EionRobb/skype4pidgin.git
cd skype4pidgin/skypeweb && mkdir build && cd build && cmake .. && sudo cpack && sudo apt-get remove pidgin-skype && apt-get install skypeweb-*.deb

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read
