#!/bin/bash

echo "### INSTALAÇÃO UBUNTU TWEAK ###"
echo " "

echo "Qual a sua versão do Ubuntu?"
echo " "
echo "1- Ubuntu 16.04"
echo "2- Ubuntu 15.10 ou inferior"
echo "3- Sair sem alteração"

read op

if [$op == 1];
then
    wget http://archive.getdeb.net/ubuntu/pool/apps/u/ubuntu-tweak/ubuntu-tweak_0.8.7-1~getdeb2~xenial_all.deb
    sudo dpkg -i --force-depends ubuntu-tweak_0.8.7-1~getdeb2~xenial_all.deb
    sudo apt-get install -f

elif [$op == 2];
then
    sudo add-apt-repository ppa:tualatrix/ppa
    sudo apt-get update
    sudo apt-get install ubuntu-tweak -y

elif [$op == 3];
then
    echo "Nenhuma alteração feita."

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read



