#!/bin/bash

echo "BlackCat Rev. 01"
echo " "

echo "### INSTALAÇÃO VLC ###"
echo " "
echo "Testado nas seguintes distribuições:"
echo "- Ubuntu 16.04"
echo " "

sudo add-apt-repository ppa:videolan/stable-daily
sudo apt-get update
sudo apt-get install vlc

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read