#!/bin/bash

echo "BlackCat Rev. 01"
echo " "
echo "### INSTALAÇÃO VIBRANCY ICON THEME ###"
echo " "

sudo add-apt-repository ppa:upubuntu-com/icons
sudo apt-get update
sudo apt-get install vibrancy-colors-icon-themes

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read