#!/bin/bash

echo "BlackCat Rev. 01"
echo " "
echo "### INSTALAÇÃO VIVACIOUS ICON THEME ###"
echo " "

sudo add-apt-repository ppa:upubuntu-com/icons
sudo apt-get update
sudo apt-get install vivacious-colors-icons