#!/bin/bash

echo "BlackCat Rev. 01"
echo " "

echo "### INSTALAÇÃO NUMIX ICON THEME CIRCLE ###"
echo " "
echo "Testado nas seguintes distribuições:"
echo "- Ubuntu 16.04"
echo "- Ubuntu 15.10"
echo "- Ubuntu 14.04"
echo " "

sudo add-apt-repository ppa:numix/ppa
sudo apt-get update
sudo apt-get install numix-icon-theme-circle -y

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read
