#!/bin/bash

echo "BlackCat Rev. 01"
echo " "
echo "### INSTALAÇÃO SHADOW ICON THEME ###"
echo " "

sudo add-apt-repository ppa:upubuntu-com/icons
sudo apt-get update
sudo apt-get install shadow-icon-theme

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read