#!/bin/bash

## Atualização 23/03/2015

# Mudando para PPA e deixando de lado a compilação

echo "### INSTALAÇÃO WHATSAPP PURPLE ###"
echo " "
sudo add-apt-repository ppa:whatsapp-purple/ppa
sudo apt-get update
sudo apt-get install pidgin-whatsapp pidgin -y

## METODO DE COMPILAÇÂO
#sudo apt-get install git pidgin python2.7 python-dateutil python-argparse libglib2.0.0 libglib2.0-dev libpurple-dev git make g++
#git clone https://github.com/davidgfnet/whatsapp-purple
#cd ~/whatsapp-purple && make
#sudo cp -rf ~/whatsapp-purple/libwhatsapp.so /usr/lib/pidgin/


# CLONANDO YOWSUP E DANDO PRIVILÉGIOS
git clone https://github.com/tgalal/yowsup.git
chmod +x ~/yowsup/yowsup-cli
clear
echo "### OBTENDO SENHA DO WHATSAPP - SIGA OS PASSOS ATENTAMENTE ###"
echo " "
echo "<< Somente obtenha a senha de um número que não está conectado
em nenhum outro dispositivo, seja ele celular ou tablet. 
Após obter a senha e conectar com ela no Pidgin NÃO conecte 
em outro dispositivo pois isso fará com que a senha seja mudada 
ocultamente somente para o celular ou tablet, logo terá que 
repetir o processo para acessar novamente pelo Pidgin. >>"
echo " "
echo " "
echo "Entre com o código do país. Ex.: 55"
read cod
echo " "
echo "Entre com seu número de celular. Ex.: 553591234567"
read phone
./yowsup/yowsup-cli registration --requestcode sms --phone $phone  --cc $cod
echo " "
echo " "
echo "Tecle ENTER - Verifique no código se a mensagem foi enviada.(importante)"
read
clear
echo "### OBTENDO SENHA DO WHATSAPP - SIGA OS PASSOS ATENTAMENTE ###"
echo " "
echo "Espere chegar uma mensagem com um 'code' em seu número"
echo " "
echo " "
echo "Informe o code de seis dígitos. Ex.: 123456 (sem hífen)"
read code
./yowsup/yowsup-cli registration --register $code --phone $phone --cc $cod
echo " "
echo "Pode observar que gerou uma lista se não apresentou nenhum erro, 
mas nela importa somente o 'pw' que é a sua senha e o login que é seu numero.
Após isso é só fazer o login pelo Pidgin já com o Whatsapp-Purple."

echo " "
echo "Processo Concluído!!! Tecle ENTER"
rm -rf ~/yowsup

read
