#!/bin/bash

echo "### INSTALAÇÃO POPCORN TIME ###"
echo " "
sudo add-apt-repository ppa:webupd8team/popcorntime
sudo apt-get update
sudo apt-get install popcorn-time -y
echo " "
echo "Processo Concluído!!! Tecle ENTER"
read
