#!/bin/bash

echo "### INSTALAÇÃO ORACLE JAVA 1.8 ###"
echo " "
sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer -y
echo " "
echo "Processo Concluído!!! Tecle ENTER"
read
