#!/bin/bash

#BlackCat Rev. 01

echo "### INSTALAÇãO TOR BROWSER ###"
echo " "

sudo add-apt-repository ppa:ricotz/docky
sudo apt-get update
sudo apt-get install plank

echo "plank --preferences para configurar"

echo "Processo Concluído!!! Tecle ENTER"
read