#!/bin/bash

#BlackCat Rev. 01
echo " "

echo "### INSTALAÇÃO SUBTERFUGE ###"
echo " "
echo "Testado nas seguintes distribuições:"
echo "- Ubuntu 16.04"
echo " "

sudo cd /.cacheappinstall/ && wget -c https://subterfuge.googlecode.com/files/subterfuge_1.0-1_all.deb
sudo apt-get install python-pip -y
sudo pip install Django==1.3
sudo dpkg -i /.cacheappinstall/subterfuge_1.0-1_all.deb
sudo apt-get -f install

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read
