#!/bin/bash

#BlackCat Rev. 01

echo "### INSTALAÇãO TOR BROWSER ###"
echo " "

sudo add-apt-repository ppa:webupd8team/tor-browser
sudo apt-get update
sudo apt-get install tor-browser

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read