#!/bin/bash

echo "### INSTALAÇÃO UBUNTU TWEAK ###"
echo " "

sudo add-apt-repository ppa:tualatrix/ppa
sudo apt-get update
sudo apt-get install ubuntu-tweak -y

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read
