#!/bin/bash

#BlackCat Rev. 01

echo "### INSTALAÇãO VLC ###"
echo " "

sudo add-apt-repository ppa:videolan/stable-daily
sudo apt-get update
sudo apt-get install vlc

echo " "
echo "Processo Concluído!!! Tecle ENTER"
read